version: "3.8"

services:
  nuxt3-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      text: ars
      API_ENDPOINT : ${NUXT_PUBLIC_API_URL}

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    restart: unless-stopped
